#!/bin/sh
PYFIGLET='./pyfiglet'
OUTPUT='./pyfiglet_example.txt'

cd "$(dirname "$0")"
if [ ! -f "$PYFIGLET" ]; then
    echo "Error ! can't find $PYFIGLET!"
fi

#. strip \' \, \[ \] from font lists of pyfiglet.
FONTS="$("$PYFIGLET" -l | sed -e "s/[',]//g" -e 's/^\[//g' -e 's/\]$//g')"

rm "$OUTPUT" 2>/dev/null
for font in $FONTS; do
    echo "$font" | tee -a "$OUTPUT"
    "$PYFIGLET" pyfiglet -f "$font" | tee -a "$OUTPUT"
done
